Create database AGENCE_IMMOBILIER
/
USE AGENCE_IMMOBILIER
/





BACKUP DATABASE AGENCE_IMMOBILIER
TO DISK = "C:\Users\kawthar\OneDrive\Bureau\GESTION D'AGENCE IMMOBILIERE\backup database"
WITH DIFFERENTIAL
/